//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_proj_ostateczny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csprojEntities : DbContext
    {
        public csprojEntities()
            : base("name=csprojEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Motorniczy> Motorniczy { get; set; }
        public virtual DbSet<Przystanki> Przystanki { get; set; }
        public virtual DbSet<Przystanki_na_trasie> Przystanki_na_trasie { get; set; }
        public virtual DbSet<Tramwaje> Tramwaje { get; set; }
        public virtual DbSet<Trasy> Trasy { get; set; }
    }
}
