//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_proj_ostateczny
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Reprezentacja tabeli motorniczy.
    /// </summary>
    public partial class Motorniczy : IdClass
    {
        public override int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int id_tramwaju { get; set; }
    
        public virtual Tramwaje Tramwaje { get; set; }
    }
}
