//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_proj_ostateczny
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Reprezentacja tabeli przystanki.
    /// </summary>
    public partial class Przystanki : IdClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przystanki()
        {
            this.Przystanki_na_trasie = new HashSet<Przystanki_na_trasie>();
        }
    
        public override int id { get; set; }
        public string nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przystanki_na_trasie> Przystanki_na_trasie { get; set; }
    }
}
