//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_proj_ostateczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramwaje : IdClass
    {
        public override int id { get; set; }
        public int numer { get; set; }
        public System.DateTime data_ostatniego_przeglądu { get; set; }
        public int id_trasy { get; set; }
    
        public virtual Trasy Trasy { get; set; }
    }
}
